### PR TITLE
Add support for sparse matrices as discussed in issue #30

### PR DESCRIPTION
**Pull request by mfeurer**

### CODE REVIEW

**Comment by renatopp** [comment]
Hey, Matthias, I'm going to take a look, in advance I can say that some tests are failing (https://travis-ci.org/renatopp/liac-arff/builds/71376128), both problems are compatibility on tests:

- Python 2.4 there is no method called `assertIsInstance`;
- Python 3.x, generators do not have `next` method (but you can use the builtin next, see 1).


1 - http://stackoverflow.com/questions/12274606/theres-no-next-function-in-a-yield-generator-in-python-3

**Comment by mfeurer** [comment]
Hi Renato,
please excuse this, I do not have all these environments on my local machine and didn't wait for the test. I will fix these issues.

**Comment by renatopp** [comment]
Checking this right now

**Comment by renatopp** [comment]
It's all good. Do you mind to add a section on the documentation file to describe how these options works and give some examples? I'm going to publish the new version with the documentation.

**Pull request merged**
