### PR TITLE
MNT Fixed another inappropriate bare raise

### PR DESCRIPTION
**Pull request by jnothman**
sorry for missing this the first time.

### CODE REVIEW

**Comment by jnothman** [comment]
Actually, before you do the release... wait a few minutes for me to maybe
patch something else small (that I realised when thinking about #83)

**Comment by mfeurer** [comment]
Sure, no problem.

**Comment by jnothman** [comment]
Never mind. It makes no difference.

**Comment by mfeurer** [comment]
Okay, release is out.

**Pull request merged**
