### PR TITLE
Add useful error message for BadObject exception

### PR DESCRIPTION
**Pull request by theresama**

### CODE REVIEW

**Comment by asottile** [comment]
@theresama looks like they still test against python2.6, so you'll need to put numbers in the format strings:

```python
                raise BadObject('len(inst) {0} != len(attributes) {1}'.format(
                     len(inst), len(attributes),
                ))

```

**Comment by mfeurer** [comment]
Thanks a lot for your help. I added an issue to remove python2.6 support (#57). Maybe you could simply tackle this as well and by that fix your PR ;)

**Comment by mfeurer** [comment]
Sorry for not being more specific. Could you please also drop references to python2.6 from the docs?

**Comment by theresama** [comment]
Sounds good! I also ran [pyupgrade](https://github.com/asottile/pyupgrade) against the source (only one small change).

**Pull request merged**
