### PR TITLE
New PR for #71

### PR DESCRIPTION
**Pull request by mfeurer**
Hey @janvanrijn I was too stupid to push to your branch so I created a new one with a few minor updates. Please let me know what you think.

### CODE REVIEW

**Comment by janvanrijn** [comment]
Awesome. Please expect a second PR from me (probably) this week, to make liac-arff adhere to sklearn standards

**Comment by mfeurer** [comment]
Could you please detail what standards?

**Comment by janvanrijn** [comment]
Ideally, these alerts will be removed: 

https://lgtm.com/projects/g/scikit-learn/scikit-learn/rev/pr-42d5708ca9013b5d2052362bcca1be7e45918161

**Comment by mfeurer** [comment]
That looks like the changes will be pretty harmless.

**Comment by janvanrijn** [comment]
I wouldn't create a PR if they were harmful ;)

**Pull request merged**
